services:
 jub-db:
  image: mongo:8-noble
  ports:
    - ${JUB_MONGODB_HOST_PORT:-27027}:27017
  volumes:
    - jub-db:/data/db
    - ./db/mongod.conf:/etc/mongo/mongod.conf:ro
  networks:
    - jub
  restart: unless-stopped
  command: ["mongod", "--config","/etc/mongo/mongod.conf"]
  
 jub:
  build:
    context: .
    dockerfile: ${JUB_DOCKERFILE:-Dockerfile}
  image: ${JUB_IMAGE_NAME:-jub:api-0.0.1a0}
  env_file:
    - .env.dev
  ports:
    - ${JUB_PORT:-6000}:${JUB_PORT:-6000}
  networks:
    - jub
  command: uvicorn jubapi.server:app --host ${JUB_HOST:-0.0.0.0} --port ${JUB_PORT:-6000} --reload
networks:
  jub:
    external: true
volumes:
  jub-db:
