name: Run Unit Test via Pytest  
  
on:
  push: 
    branches: ["*"]
  pull_request:
    branches: ["*"]
    paths:
      - "jubapi/**"
      - "tests/**"
      - "pyproject.toml"
jobs:  
  build:  
    runs-on: ubuntu-latest  
    env:
      JUB_LOG_PATH: ${{ github.workspace }}/log
      JUB_DEPLOY_ENV_FILE_PATH: ${{ github.workspace }}/.env.dev
      JUB_ENV_FILE_PATH: ${{ github.workspace }}/.env.test
    strategy:  
      matrix:  
        python-version: ["3.10"]  
    steps:  
      - uses: actions/checkout@v3  

      - name: Set up Python ${{ matrix.python-version }}  
        if: ${{!env.ACT}}
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      

      - name: Cache Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-2.1.3-${{ runner.os }}

      - name: Install Poetry
        run: |
          pip install poetry==2.1.3 --break-system-packages
          
          # Replicate the snok/install-poetry configuration
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

        
      - name: Load cached venv
        if: ${{!env.ACT}}
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install Dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry lock && poetry install --without docs --no-interaction

      - name: Prepare log folder
        run: mkdir -p "${JUB_LOG_PATH}"

      - name: Start Jub Service
        run: |
          chmod +x deploy.sh && ./deploy.sh ${{ env.JUB_DEPLOY_ENV_FILE_PATH || '.env.dev' }}
        env:
          JUB_ENV_FILE_PATH: ${{ env.ACT == 'true' && env.JUB_DEPLOY_ENV_FILE_PATH || '.env.dev' }}

      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff check .  
        continue-on-error: true  
        
      - name: Test with pytest  
        run: |  
          poetry run coverage run -m pytest tests/ --ignore=tests/deprecated -v -s
        env:
          JUB_ENV_FILE_PATH: ${{env.JUB_ENV_FILE_PATH || '.env.test' }}
     
      - name: Generate Coverage Report  
        run: |  
          poetry run coverage report -m
